#!/bin/bash
#inspect if the user has the follow extensions and count how many of them.

for user in /home/*
do
        MP4COUNT=0
        MP3COUNT=0
        JPGCOUNT=0
        OLDIFS=$IFS
        IFS=$'\n'
        for files in $(find $user -name '*.jpg' -o -name '*.mp3' -o -name '*.mp4')
        do
                case $files in
                        *.mp4)
                                MP4COUNT=$(expr $MP4COUNT + 1 )
                                ;;
                        *mp3)
                                MP3COUNT=$(expr $MP3COUNT + 1 )
                                ;;
                        *.jpg)
                                JPGCOUNT=$(expr $JPGCOUNT + 1 )
                                ;;
                esac
        done #Find end here

        echo "User: $(basename $user)"
        echo "JPG: $JPGCOUNT"
        echo "MP3: $MP3COUNT"
        echo "MP4: $MP4COUNT"
        echo
done
IFS=$OLFIFS
